### PR TITLE
fixes #16

### LINKED ISSUE #16: Store passwords as a hash code instead of a plaintext String
**The Problem**
At the moment, passwords are stored as a String attribute in a Bracket object. When a user tries to log into an existing account, the program uses bracketObj.getPassword() and compares it against the user's entry. This is not secure, since after serializing a Bracket you can plainly see the password stored as text in the .ser file.

**What to do instead**
The password should be stored as a byte array that has been put through a hash algorithm, which is essentially irreversible and therefore secure. A string can be converted to a hash using the SHA-256 algorithm in java with, for example, the following code:

```
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

...

byte[] stringToHash(String input) throws NoSuchAlgorithmException {
        return MessageDigest.getInstance("SHA-256").digest(input.getBytes());
}

```

Whenever a user creates a new account, the entered password should be put through a function like this and stored. When a user tries to log in to an existing account, their entered password should also be put through this function, and *then* compared to the stored byte array for that account.

Obviously, we don't really need to be concerned about building a fully secure system for a simple Java project like this, but we should do something basic to prevent the passwords being easily seen as plaintext like they currently are.

**(Edit) More specifics about this issue**

In order to check password hash keys, we need to have the hash keys of each account ready *before* actually loading a bracket. To account for this, there should be one new .txt file in the program that would be read from once when the user arrives at the login screen. This .txt file would store existing usernames and their corresponding hash keys. When a user enters an existing username, their entered password's hash should be compared to the username's corresponding hash key, and only if there is a match should the corresponding bracket be deserialized.

### PR DESCRIPTION
**Pull request by saplio**
fixes #16

### CODE REVIEW

File: src/MarchMadnessGUI.java [hunk 1]
```diff
@@ -373,7 +387,7 @@ private GridPane createLogin(){
         loginPane.setVgap(10);
         loginPane.setPadding(new Insets(5, 5, 5, 5));
 
-        Text welcomeMessage = new Text("March Madness Login Welcome");
+        Text welcomeMessage = new Text("March Madness a Welcome");
```
Comment (bertoab) [inline src/MarchMadnessGUI.java]: Is this meant to be read as "March-Madness-a welcome!" (all in one word)? I'm a little confused

File: src/MarchMadnessGUI.java
Comment (bertoab) [inline src/MarchMadnessGUI.java]: This method (`deserializeBracket`) is directly called within `loadBrackets`, which has return type `ArrayList<Bracket>`.

## Issue with outdated `.ser` files
For users who have outdated `.ser` files in their local repository directory, this `catch` statement does not properly handle the error. It shows an error message to the user, but then continues execution without setting the `bracket` variable to an actual `Bracket` object.
So, `deserializeBracket` returns `null` in this case.

1. `loadBrackets` does not verify the return type of `deserializeBracket`:
Image

2. Next, `loadBrackets` returns an `ArrayList` containing some `null` elements:

Image

 3. Lastly, `addAllToMap` will use `playerMaps` without verifying the class of each element, causing a runtime error:

Image

I laid out the method invocation chain for you because I'm not sure what the most sensible solution is.

## Simple non-destructive fix
I think a non-destructive fix would be to just skip each outdated bracket. I think showing an error message is okay, as long as the program runs after. Showing which file is causing the problem would be a bonus, in my opinion.

_To implement this solution_, I think it's just a matter of making sure that `loadBracket` checks the return value of `deserializeBracket` before adding it to the `ArrayList`; it needs to make sure it is an `instanceof Bracket`.

In this case, `deserializeBracket` isn't doing any better at handling the error, but now the only method that calls it is verifying its return value, so I think it's okay. This is the quickest fix I could think of.

File: passwordHashes.txt
Comment (bertoab) [inline passwordHashes.txt:1]: ## Concerns about tracking this file
I understand this file is included in this commit both because `loadPasswordHashes` does not create it, and because `newExample.ser` depends on it to allow a user to log in and modify the bracket.

However, adding this new file in this commit will make `passwordHashes.txt` a tracked file for Git. What this means is that after this commit is merged, anyone who makes any modifications to this file on their local repository directory will be alerted by Git to commit their changes.

For a file that stores password hashes, this does not seem appropriate to me. Simultaneously, I understand that security is not super critical for this project, so **I will still approve this if you don't take my suggestion**.
## What I suggest
I notice that `appendLoginInfo` will create this file it it doesn't already exist. Since the only other method that directly depend on this file is `loadPasswordHashes`, _a simple fix_ could be to simply return an empty `HashMap` from `loadPasswordHashes` if this file cannot be found.

After testing this, a bug that comes up is that a valid bracket file (like `newExample.ser`) cannot be logged-in to, and will instead be overwritten if a user goes on to finalize a bracket after creating a password.

I think that for the sake of the `newExample` user, that is fine; I prefer not having this password hashes file be tracked on the repository over being able to log in to this example user.

I'm open to suggestions, let me know what you think.

**Review by bertoab — CHANGES_REQUESTED** [review]
I left a couple comments on your changes to `MarchMadnessGUI.java`. The first one is very minor (just help me understand a little more) and the second one is potentially a small change as well.
I also added a comment for the `passwordHashes.txt` file. This one is not super urgent, so feel free to ignore it if you are pressed for time :)

File: passwordHashes.txt
Comment (bertoab) [reply passwordHashes.txt:1]: Decision: leave this as is for the sake of wrapping up this assignment

File: src/MarchMadnessGUI.java
Comment (bertoab) [reply src/MarchMadnessGUI.java]: Addressed by 20f9067

File: src/MarchMadnessGUI.java (hunk 1 above)
Comment (bertoab) [reply src/MarchMadnessGUI.java]: Addressed by 6843f93

**Review by bertoab — APPROVED** [review]
