### PR TITLE
Fixes #8 and Fixes #10

### LINKED ISSUE #8: Feat(): Show simulation results (wins/losses + scoring)
Description
Enhance simulation output to include:

- Which teams won/lost (simulation)

- Game scores

- Points earned per correct prediction

### LINKED ISSUE #10: Feat(): Visual comparison between predicted and actual bracket
Description
Add visual feedback comparing predicted vs actual results:

Correct predictions → green

Incorrect predictions → red

### PR DESCRIPTION
**Pull request by mtumminomassbay**
Fixes #8 and Fixes #10
Also includes updating Help and Cycle buttons to match other buttons

### CODE REVIEW

File: src/Bracket.java [hunk 1]
```diff
@@ -209,28 +209,73 @@ public boolean isSubtreeComplete(int root)
...
+
+        //Adjustment by Matthew Tummino
+        //Accounts for the box score being added to the winner names in the bracket
+        for(int i = 0; i < 63; i++)
+        {
+            String masterString = master.getBracket().get(i);
+            int stopIndex = masterString.indexOf("[");
+            if (stopIndex != -1)
+                masterString = masterString.substring(0, stopIndex-1);
+            System.out.println(masterString);
```
Comment (mtumminomassbay) [inline src/Bracket.java]: Just realized I left in this printLn from when I was still testing this. This should be removed

**Review by bertoab — APPROVED** [review]
